# -*- coding: utf-8 -*-
"""Build tables.tex for the eSSVI-calibration study, entirely from the CSVs.

Six arms: essvi_sg05 (greedy sequential backbone, guaranteed, gamma 1/2),
essvi_g05 / essvi_gfree (global, Mingone 2022, arbitrage-free by
construction, power-law psi backbone with gamma fixed at 1/2 or fitted),
essvi (sequential + penalties), ssvi (global power-law SSVI), svi (the
unstructured benchmark). Universe: four index ETFs (SPY, QQQ, IWM, DIA)
and four single names (META, AMD, TSLA, GOOGL) over nineteen sessions,
2026-08-14 to 2026-09-11, expiries 1 day to 1.5 years; JPM and XOM run
as an extension under results/extension/.

Optional inputs. The intraday result CSVs (results/intraday/) and the
fitted-exponent panel (results/gamma_ext.csv) come from the intraday
captures, which are not in the public repository. Without the first,
intraday entries print as '--'; without the second, the two exponent
tables (tables_gamma.tex, tables_gammaext.tex) are not written.
"""
import pandas as pd, numpy as np, json, os

_HERE = os.path.dirname(os.path.abspath(__file__))
R    = os.path.join(_HERE, 'results').replace('\\', '/')
TEX  = os.path.join(_HERE, 'tables.tex').replace('\\', '/')
TEXA = os.path.join(_HERE, 'tables_appendix.tex').replace('\\', '/')
BOOL = {'true': True, 'false': False, True: True, False: False}

def rcsv(path, **kw):
    """Read a released CSV, plain or gzipped."""
    if not os.path.exists(path) and os.path.exists(path + '.gz'):
        path += '.gz'
    return pd.read_csv(path, **kw)
def tobool(s):
    return s.map(lambda v: BOOL.get(v, np.nan))
def med(s):
    s = pd.Series(s).dropna().astype(float)
    return np.nan if len(s) == 0 else float(np.median(s))
def pc(s, p):
    s = pd.Series(s).dropna().astype(float)
    return np.nan if len(s) == 0 else float(np.percentile(s, p))
def f(x, d=2):
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return '--'
    return f'{x:,.{d}f}'.replace(',', r'\,')
def i(x):
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return '--'
    return f'{int(x):,}'.replace(',', r'\,')
def n_(k, frame):
    """A count, or '--' when its source frame is empty (intraday CSVs absent)."""
    return '--' if len(frame) == 0 else i(k)

# display order: the eSSVI arms first, the benchmark last
MODELS  = ['essvi_sg05', 'essvi_g05', 'essvi_gfree', 'essvi', 'ssvi', 'svi']
# the "practical menu" whose cross-model spread is the headline (benchmark out)
MENU    = ['essvi_sg05', 'essvi_g05', 'essvi_gfree', 'essvi', 'ssvi']
GLOBALS = ['essvi_g05', 'essvi_gfree']
GUARANTEED = ['essvi_sg05', 'essvi_g05', 'essvi_gfree']
MNAME = {'essvi_sg05': r'S-eSSVI ($\gamma{=}\tfrac12$)',
         'essvi_g05':  r'G-eSSVI ($\gamma{=}\tfrac12$)',
         'essvi_gfree': r'G-eSSVI ($\gamma$ free)',
         'essvi':       'eSSVI (seq.)',
         'ssvi':        'SSVI',
         'svi':         'SVI (benchmark)'}
# the same names split over two lines, for a spanning header that
# would otherwise set the width of the two numeric columns under it
MSTACK = {'essvi_sg05':  ('S-eSSVI', r'$\gamma{=}\tfrac12$'),
          'essvi_g05':   ('G-eSSVI', r'$\gamma{=}\tfrac12$'),
          'essvi_gfree': ('G-eSSVI', r'$\gamma$ free'),
          'essvi':       ('eSSVI',   '(seq.)'),
          'ssvi':        ('SSVI',    '{}'),
          'svi':         ('SVI',     '(bench.)')}
TICKS = ['SPY', 'QQQ', 'IWM', 'DIA', 'META', 'AMD', 'TSLA', 'GOOGL']
IDX   = ['SPY', 'QQQ', 'IWM', 'DIA']
SGL   = ['META', 'AMD', 'TSLA', 'GOOGL']

# ------------------------------------------------------------------ load
# The intraday result CSVs are supplied on request rather than released.
# Without them every intraday entry prints as '--'; the daily tables are
# unaffected.
HAVE_INTRADAY = os.path.exists(f'{R}/intraday/panel.csv') or os.path.exists(f'{R}/intraday/panel.csv.gz')
def rcsv_i(name, like):
    return rcsv(f'{R}/intraday/{name}') if HAVE_INTRADAY else like.iloc[0:0].copy()
panel  = rcsv(f'{R}/panel.csv');       paneli = rcsv_i('panel.csv', panel)
fits   = rcsv(f'{R}/fits.csv');        fitsi  = rcsv_i('fits.csv', fits)
arb    = rcsv(f'{R}/arbitrage.csv');   arbi   = rcsv_i('arbitrage.csv', arb)
lv     = rcsv(f'{R}/localvol.csv');    lvi    = rcsv_i('localvol.csv', lv)
mart   = rcsv(f'{R}/martingale.csv');  marti  = rcsv_i('martingale.csv', mart)
tim    = rcsv(f'{R}/timing.csv');      timi   = rcsv_i('timing.csv', tim)
if not HAVE_INTRADAY:
    print('note: results/intraday/ not found; intraday entries print as --')

# Each table is written to its own tables_<name>.tex so the paper can
# \input it beside the prose and figure it belongs with.
blocks = {}
W = None
def block(name):
    global W
    b = []
    blocks[name] = b
    W = b.append
    W(r'% tables_' + name + r'.tex -- generated by make_tables.py from the released')
    W(r'% CSVs; do not edit by hand. Every number is computed, none transcribed.')
    W('')

# ================================================= APPENDIX TABLES: panel
# The panel/attrition detail moved to the appendix (tables_appendix.tex):
# Table A -- the cleaning cascade per rule; Table B -- what the fits
# actually received, per name and per tenor bucket.
ok_d, fail_d = panel[panel.status == 'ok'], panel[panel.status != 'ok']
ok_i, fail_i = paneli[paneli.status == 'ok'], paneli[paneli.status != 'ok']

outA = []
A = outA.append
A(r'% ---------------------------------------------------------------------------')
A(r'% tables_appendix.tex -- panel detail for the eSSVI calibration study.')
A(r'% Generated by make_tables.py; do not edit by hand.')
A(r'% ---------------------------------------------------------------------------')
A('')

DROPS = [('drop_unquoted_or_crossed', r'unq.'),
         ('drop_wide_spread',         r'spread'),
         ('drop_expiry_window',       r'expiry'),
         ('drop_moneyness_window',    r'mny.'),
         ('drop_in_the_money',        r'ITM')]
OTHER = ['drop_vol_out_of_bounds', 'drop_solver_failed', 'drop_sparse_expiry',
         'drop_no_forward']

A(r'\begin{table}[tbp]')
A(r'\centering')
A(r'\caption{\textbf{Quote attrition: where the raw chain goes.} Median quote '
  r'counts per capture through the shared cleaning cascade, applied once '
  r'upstream of all six arms. Rules in application order: unquoted, crossed or '
  r'zero-bid (unq.); relative spread above 25\% (spread); expiry outside '
  r'1 day--1.5 years (expiry); $K/F$ outside $[0.6, 1.6]$ (mny.); the '
  r'in-the-money side of each strike (ITM); and the residual rules (other: vol '
  r'bounds, failed inversions, expiries left with fewer than five quotes). '
  r'Failures are captures on which no expiry survives.}')
A(r'\label{tab:attrition}')
A(r'\footnotesize')
A(r'\setlength{\tabcolsep}{4.5pt}')
A(r'\begin{tabular}{lrrrrrrrrrrr}')
A(r'\toprule')
A(r'& & & & \multicolumn{6}{c}{Median quotes dropped, by rule} & & \\')
A(r'\cmidrule(lr){5-10}')
A(r'Ticker & Capt. & Fail & Raw & unq. & spread & expiry & mny. & ITM & other '
  r'& Used & Kept \% \\')
A(r'\midrule')
def attr_row(label, dd, okd):
    other = okd[OTHER].sum(axis=1)
    A(f'{label} & {n_(len(dd), dd)} & {n_((dd.status!="ok").sum(), dd)} & {i(med(dd.n_quotes_raw))} & '
      + ' & '.join(i(med(okd[c])) for c, _ in DROPS) + f' & {i(med(other))} & '
      f'{i(med(okd.n_quotes_used))} & {f(100*med(okd.n_quotes_used/okd.n_quotes_raw),1)} \\\\')
A(r'\multicolumn{12}{l}{\textit{Daily (15:30) slice}} \\')
for t in TICKS:
    d = panel[panel.ticker == t]
    attr_row(r'\quad ' + t, d, d[d.status == 'ok'])
A(r'\midrule')
attr_row('All daily', panel, ok_d)
attr_row('All intraday', paneli, ok_i)
A(r'\bottomrule')
A(r'\end{tabular}')
A(r'\end{table}')
A('')

# Table B: what the fits received -- per name, then per tenor bucket.
sv  = fits[(fits.status == 'ok') & (fits.model == 'svi')].copy()
def qexp(dd):
    q1, q3 = pc(dd.n_quotes_used, 25), pc(dd.n_quotes_used, 75)
    return f'{i(med(dd.n_quotes_used))} [{i(q1)}, {i(q3)}]'
A(r'\begin{table}[tbp]')
A(r'\centering')
A(r'\caption{\textbf{What the fits received.} Top: the fitting input and the '
  r'static-arbitrage repair per name (daily slice, medians per capture): '
  r'expiry slices, pillar quotes per capture and per expiry, butterfly and '
  r'calendar violations in the \emph{raw} quotes, repair adjustments applied, '
  r'and the largest single vol change the repair made (absolute implied vol; '
  r'0.01 is one volatility point). Bottom: the same pillar quotes pooled by '
  r'tenor bucket.}')
A(r'\label{tab:fitinput}')
A(r'\footnotesize')
A(r'\setlength{\tabcolsep}{4.5pt}')
A(r'\begin{tabular}{lrrrrrrr}')
A(r'\toprule')
A(r'\multicolumn{8}{l}{\textit{Per name (daily)}} \\')
A(r'Ticker & Expiries & Quotes & Quotes/expiry & Raw bfly & Raw cal. & Repairs '
  r'& Max $\Delta$vol \\')
A(r'\midrule')
for t in TICKS:
    okd = ok_d[ok_d.ticker == t]
    svt = sv[sv.ticker == t]
    A(f'{t} & {i(med(okd.n_expiries_used))} & {i(med(okd.n_quotes_used))} & {qexp(svt)} & '
      f'{i(med(okd.raw_butterfly_violations))} & {i(med(okd.raw_calendar_violations))} & '
      f'{i(med(okd.repair_butterfly_adjustments + okd.repair_calendar_adjustments))} & '
      f'{f(med(okd.repair_max_vol_change),3)} \\\\')
A(r'\midrule')
A(r'\multicolumn{8}{l}{\textit{Per tenor bucket (daily, all names)}} \\')
A(r'Bucket & Slices & & Quotes/expiry & \multicolumn{2}{c}{Median $[k_{lo}, k_{hi}]$} & & \\')
A(r'\midrule')
sv['bucket'] = sv.tenor_years.map(
    lambda t: r'$\le$1W' if t <= 7/365 else '1W--1M' if t <= 1/12
    else '1--6M' if t <= 0.5 else r'$>$6M')
for b in [r'$\le$1W', '1W--1M', '1--6M', r'$>$6M']:
    dd = sv[sv.bucket == b]
    A(f'{b} & {i(len(dd))} & & {qexp(dd)} & '
      f'[{f(med(dd.k_lo),2)}, & {f(med(dd.k_hi),2)}] & & \\\\')
A(r'\bottomrule')
A(r'\end{tabular}')
A(r'\end{table}')
A('')

# =========================================================== TABLE 2: fit
block('fit')
fo  = fits[fits.status == 'ok'].copy()
foi = fitsi[fitsi.status == 'ok'].copy()
def bucket(t):
    return r'$\le$1W' if t <= 7/365 else '1W--1M' if t <= 1/12 else '1--6M' if t <= 0.5 else r'$>$6M'
for d in (fo, foi):
    d['bucket'] = d.tenor_years.map(bucket)
BUCKETS = [r'$\le$1W', '1W--1M', '1--6M', r'$>$6M']

med_g05 = med(fo[fo.model == 'essvi_g05'].fit_rmse_vol_bp)
med_gfr = med(fo[fo.model == 'essvi_gfree'].fit_rmse_vol_bp)
med_seq = med(fo[fo.model == 'essvi'].fit_rmse_vol_bp)
med_svi = med(fo[fo.model == 'svi'].fit_rmse_vol_bp)
med_sg5 = med(fo[fo.model == 'essvi_sg05'].fit_rmse_vol_bp)
gam = fo[fo.model == 'essvi_gfree'].groupby(['ticker','date','time']).essvi_gamma.first()

W(r'\begin{table}[tbp]')
W(r'\centering')
W(r'\caption{\textbf{Fit quality across the six arms.} Per-slice root-mean-square residual '
  r'against the shared repaired pillars, in implied-volatility basis points: medians and 90th '
  r'percentiles. Bucket $n$ is the number of expiry slices, identical across arms because '
  r'every arm fits the same pillars.}')
W(r'\label{tab:fit}')
W(r'\scriptsize')
W(r'\setlength{\tabcolsep}{3.6pt}')
W(r'\begin{tabular}{lr' + 'rr'*len(MODELS) + '}')
W(r'\toprule')
W(r'& & ' + ' & '.join(r'\multicolumn{2}{c}{\shortstack{' + MSTACK[m][0]
  + r'\\' + MSTACK[m][1] + '}}' for m in MODELS) + r' \\')
W(''.join(f'\\cmidrule(lr){{{3+2*j}-{4+2*j}}}' for j in range(len(MODELS))))
W(r'Stratum & Slices & ' + ' & '.join('Med. & p90' for _ in MODELS) + r' \\')
W(r'\midrule')
W(r'\multicolumn{' + str(2+2*len(MODELS)) + r'}{l}{\textit{By tenor bucket (daily)}} \\')
for b in BUCKETS:
    d = fo[fo.bucket == b]
    n = len(d[d.model == 'svi'])
    cells = []
    for m in MODELS:
        s = d[d.model == m].fit_rmse_vol_bp
        cells += [f(med(s), 1), f(pc(s, 90), 0)]
    W(f'\\quad {b} & {i(n)} & ' + ' & '.join(cells) + r' \\')
W(r'\addlinespace')
W(r'\multicolumn{' + str(2+2*len(MODELS)) + r'}{l}{\textit{By ticker (daily)}} \\')
for t in TICKS:
    d = fo[fo.ticker == t]
    n = len(d[d.model == 'svi'])
    cells = []
    for m in MODELS:
        s = d[d.model == m].fit_rmse_vol_bp
        cells += [f(med(s), 1), f(pc(s, 90), 0)]
    W(f'\\quad {t} & {i(n)} & ' + ' & '.join(cells) + r' \\')
W(r'\addlinespace')
for lab, d in [('All daily slices', fo), ('All intraday slices', foi)]:
    cells = []
    for m in MODELS:
        s = d[d.model == m].fit_rmse_vol_bp
        cells += [f(med(s), 1), f(pc(s, 90), 0)]
    W(f'{lab} & {n_((d.model=="svi").sum(), d)} & ' + ' & '.join(cells) + r' \\')
W(r'\midrule')
W(r'\multicolumn{' + str(2+2*len(MODELS)) + r'}{l}{\textit{Solver outcome '
  r'(\% of fitted slices; daily / intraday)}} \\')
for lab, col in [('Converged', 'converged'), ('Passes own conditions', 'self_validates')]:
    cells = []
    for m in MODELS:
        cells += [f(100 * tobool(fo[fo.model == m][col].astype(str).str.lower()).mean(), 1)
                  if fo[fo.model == m][col].dtype == object else f(100 * fo[fo.model == m][col].mean(), 1),
                  f(100 * foi[foi.model == m][col].mean(), 1)]
    W(f'\\quad {lab} & & ' + ' & '.join(cells) + r' \\')
W(r'\bottomrule')
W(r'\end{tabular}')
W('')
W(r'\begin{minipage}{\textwidth}\footnotesize\vspace{0.4em}')
tc = fo[fo.model.isin(GUARANTEED)].groupby(['model','ticker','date','time']).agg(
        n=('slice_index','size'), cl=('essvi_tube_clamped','first')).reset_index()
W(r"``Passes own conditions'' applies each model's own parameter-level "
  r'sufficient no-arbitrage conditions to its own fitted parameters. It is a '
  r'certificate the model issues about itself rather than a measured violation '
  r'count (Table~\ref{tab:arbitrage} measures the surfaces), and the conditions '
  r'differ by model, so the column is not a like-for-like comparison across arms.')
W(r'\end{minipage}')
W(r'\end{table}')
W('')

# ==================================================== TABLE: leave-one-expiry-out
block('loo')
loo = rcsv(f'{R}/loocv.csv')
lok = loo[loo.status == 'ok'].copy()
lok['bucket'] = lok.tenor_years.map(bucket)
lok['ratio'] = lok.loo_rmse_bp / lok.insample_rmse_bp.where(lok.insample_rmse_bp > 0)

W(r'\begin{table}[tbp]')
W(r'\centering')
W(r'\caption{\textbf{Out of sample: the leave-one-expiry-out test (daily slice).} '
  r'Each interior pillar is held out in turn, every arm refitted on the rest and '
  r'evaluated at the held-out strikes. Both errors are measured against the same '
  r'repaired pillar vols, in implied-volatility basis points, so their ratio measures '
  r'what interpolation costs.}')
W(r'\label{tab:loo}')
W(r'\footnotesize')
W(r'\setlength{\tabcolsep}{3.4pt}')
W(r'\begin{tabular}{lrrrrrrrrr}')
W(r'\toprule')
W(r'& & In-sample & \multicolumn{2}{c}{LOO RMSE (bp)} & LOO/IS & ATM bias & '
  r'\multicolumn{3}{c}{LOO median by tenor (bp)} \\')
W(r'\cmidrule(lr){4-5}\cmidrule(lr){8-10}')
W(r'Model & $n$ & med.\ bp & med. & [IQR] & med. & med.\ bp & '
  r'$\le$1M & 1--6M & $>$6M \\')
W(r'\midrule')
for m in MODELS:
    x = lok[lok.model == m]
    short = x[x.tenor_years <= 1/12]
    mid_  = x[(x.tenor_years > 1/12) & (x.tenor_years <= 0.5)]
    long_ = x[x.tenor_years > 0.5]
    W('\\quad ' + MNAME[m] + ' & ' + i(len(x)) + ' & '
      + f(med(x.insample_rmse_bp), 1) + ' & '
      + f(med(x.loo_rmse_bp), 1) + ' & '
      + '[' + f(pc(x.loo_rmse_bp, 25), 1) + ', ' + f(pc(x.loo_rmse_bp, 75), 1) + '] & '
      + f(med(x.ratio), 2) + ' & '
      + f(med(x.loo_atm_signed_bp), 1) + ' & '
      + f(med(short.loo_rmse_bp), 1) + ' & '
      + f(med(mid_.loo_rmse_bp), 1) + ' & '
      + f(med(long_.loo_rmse_bp), 1) + r' \\')
W(r'\bottomrule')
W(r'\end{tabular}')
W('')
W(r'\begin{minipage}{\textwidth}\footnotesize\vspace{0.4em}')
_fails = loo[loo.status != 'ok']
W(r'One row per (capture, arm, held-out interior expiry). \emph{In-sample} is the '
  r'full fit{\textquotesingle}s RMSE at the same held-out expiries, so the LOO/IS '
  r'ratio compares like with like (medians of per-row ratios). \emph{ATM bias} is '
  r'the signed error, model minus market, at the quote nearest the forward; '
  r'negative means the interpolated smile sits below the market at the money.')
W(r'\end{minipage}')
W(r'\end{table}')
W('')

# ==================================================== TABLE: fitted exponents
# Both come from the --panel gamma run on the intraday captures; the
# public repository does not ship it, so they are built only when present.
BS = chr(92)
HAVE_GAMMA = os.path.exists(f'{R}/gamma_ext.csv') or os.path.exists(f'{R}/gamma_ext.csv.gz')
def _exponent_tables():
    block('gamma')
    # Both exponent tables come from the --panel gamma run. Its G-eSSVI fit is
    # the intraday panel's own fit (same ingest, same code path), which the
    # assertion below checks on the names the two files share.
    gx = rcsv(f'{R}/gamma_ext.csv')
    gx = gx[gx.status == 'ok'].copy()
    LIQ_EXTRA = ['AAPL', 'MSFT', 'AMZN', 'NVDA', 'JPM', 'XOM']
    THIN_EXTRA = ['CLX', 'CRI', 'DPZ', 'ETSY', 'FIVE', 'KMX', 'OLN', 'THO', 'WEN', 'WHR']

    def gx_series(model, ticker=None):
        # ticker=None pools the STUDY panel (the eight names), never the extras
        d = gx[gx.model == model]
        d = d[d.ticker == ticker] if ticker is not None else d[d.ticker.isin(TICKS)]
        return d.groupby(['ticker', 'date', 'time']).gamma.first()

    def gx_row(model, ticker=None):
        g = gx_series(model, ticker)
        return (f(med(g), 3), f(pc(g, 25), 3), f(pc(g, 75), 3), f(100 * (g > 0.5).mean(), 0), len(g))

    def gx_row_all(model):
        return gx_row(model, None)

    def at_bound(ticker=None):
        g = gx_series('ssvi', ticker)
        return 100 * (g > 0.4999).mean()

    # the intraday panel and the gamma panel must agree on the G-eSSVI exponent
    try:
        _fi = foi[foi.model == 'essvi_gfree'].groupby(['ticker', 'date', 'time']).essvi_gamma.first()
        _gi = gx_series('essvi_gfree')
        _j = _fi.to_frame('a').join(_gi.to_frame('b'), how='inner').dropna()
        _gap = float((_j.a - _j.b).abs().max()) if len(_j) else float('nan')
        print(f'gamma cross-check: {len(_j)} shared captures, max |gamma(intraday) - gamma(gamma panel)| = {_gap:.2e}')
    except Exception as _e:  # the intraday panel may not have been run yet
        print('gamma cross-check skipped:', _e)

    ALLB = at_bound()

    W(r'\begin{table}[tbp]')
    W(r'\centering')
    W(r'\caption{\textbf{The fitted exponent, name by name.} Median [IQR] of the '
      r'fitted power-law exponent per capture on the intraday slice, and the share '
      r'of captures above $\tfrac12$. The second block is the unconstrained SSVI '
      r'refit, a diagnostic: the SSVI arm itself is calibrated inside '
      r'$(0,\tfrac12]$ and sits on the bound on '
      + f(sum(at_bound(t) * len(gx_series("ssvi", t)) for t in TICKS) / sum(len(gx_series("ssvi", t)) for t in TICKS), 0)
      + r'\% of these captures.}')
    W(r'\label{tab:gamma}')
    W(r'\small')
    W(r'\begin{tabular}{lrrrrrr}')
    W(r'\toprule')
    W(r'& \multicolumn{3}{c}{G-eSSVI ($\gamma$ free)} & \multicolumn{3}{c}{SSVI, exponent unconstrained} \\')
    W(r'\cmidrule(lr){2-4}\cmidrule(lr){5-7}')
    W(r'Ticker & Med. & IQR & $>\tfrac12$ (\%) & Med. & IQR & $>\tfrac12$ (\%) \\')
    W(r'\midrule')
    for t in TICKS + ['All']:
        if t == 'All':
            W(r'\midrule')
        tk = None if t == 'All' else t
        a_ = gx_row('essvi_gfree', tk) if tk else gx_row_all('essvi_gfree')
        b_ = gx_row('ssvi_free', tk) if tk else gx_row_all('ssvi_free')
        W(f'{t} & {a_[0]} & [{a_[1]}, {a_[2]}] & {a_[3]} & '
          f'{b_[0]} & [{b_[1]}, {b_[2]}] & {b_[3]} ' + BS + BS)
    W(r'\bottomrule')
    W(r'\end{tabular}')
    W(r'\end{table}')
    W('')

    # ============================== APPENDIX: the fitted exponent, wider cross-section
    block('gammaext')
    W(r'\begin{table}[tbp]')
    W(r'\centering')
    _omit = [t for t in LIQ_EXTRA + THIN_EXTRA if gx_row('essvi_gfree', t)[4] < 100]
    W(r'\caption{\textbf{The fitted exponent over a wider cross-section.} As '
      r'Table~\ref{tab:gamma}, extended to sixteen further single names fitted for '
      r'the exponent only, with identical ingest. $n$ is the number of intraday '
      r'captures that survive the quote filters and fit; names with fewer than 100 ('
      + ', '.join(_omit) + r') are omitted. JPM and XOM also run through the full '
      r'pipeline in Section~\ref{sec:res-thin}.}')
    W(r'\label{tab:gammaext}')
    W(r'\footnotesize')
    W(r'\setlength{\tabcolsep}{3.5pt}')
    W(r'\begin{tabular}{lrrrrrrr}')
    W(r'\toprule')
    W(r'& & \multicolumn{3}{c}{G-eSSVI ($\gamma$ free)} & \multicolumn{3}{c}{SSVI, exponent unconstrained} \\')
    W(r'\cmidrule(lr){3-5}\cmidrule(lr){6-8}')
    W(r'Ticker & $n$ & Med. & IQR & $>\tfrac12$ (\%) & Med. & IQR & $>\tfrac12$ (\%) \\')
    W(r'\midrule')
    for grp, names in [('Index ETFs (study panel)', IDX),
                       ('Single names (study panel)', SGL),
                       ('Liquid single names', LIQ_EXTRA),
                       ('Thinner single names', THIN_EXTRA)]:
        W(r'\multicolumn{8}{l}{\textit{' + grp + r'}} ' + BS + BS)
        for t in names:
            a_ = gx_row('essvi_gfree', t)
            b_ = gx_row('ssvi_free', t)
            if a_[4] < 100:
                # too few surviving captures to characterise; named in the caption instead
                continue
            W(r'\quad ' + f'{t} & {a_[4]} & {a_[0]} & [{a_[1]}, {a_[2]}] & {a_[3]} & '
              f'{b_[0]} & [{b_[1]}, {b_[2]}] & {b_[3]} ' + BS + BS)
        W(r'\addlinespace')
    W(r'\bottomrule')
    W(r'\end{tabular}')
    W(r'\end{table}')
    W('')

if HAVE_GAMMA:
    _exponent_tables()
else:
    print('note: results/gamma_ext.csv not found; the two exponent tables are not written')


# ================================================ TABLE: two thin chains
block('thin')
E = f'{R}/extension'
THIN = ['JPM', 'XOM']; THINREF = ['DIA', 'SPY']; FOUR = THIN + THINREF
def _both(name, **kw):
    a_ = rcsv(f'{E}/{name}.csv', **kw); b_ = rcsv(f'{R}/{name}.csv', **kw)
    x_ = pd.concat([a_[a_.ticker.isin(THIN)], b_[b_.ticker.isin(THINREF)]], ignore_index=True)
    if 'status' in x_.columns:
        x_ = x_[x_.status.astype(str).str.startswith('ok')]
    return x_
tp_ = _both('panel'); tp_ = tp_[tp_.slice == 'daily']
tf_ = _both('fits'); ta_ = _both('arbitrage'); tl_ = _both('localvol')
tb_ = _both('barriers'); tlo_ = _both('loocv')
tb_['barrier_dir'] = tb_.barrier_dir.fillna('none')
tlo_['ratio'] = tlo_.loo_rmse_bp / tlo_.insample_rmse_bp.where(tlo_.insample_rmse_bp > 0)
def _percap(df, model, fn):
    out = []
    for (_t, _d), c_ in df[df.model == model].groupby(['ticker', 'date']):
        c_ = c_.sort_values('tenor_years')
        out.append((_t, fn(c_)))
    return pd.DataFrame(out, columns=['ticker', 'v'])
_psi_inc = _percap(tf_, 'essvi_g05', lambda c_: (np.diff(c_.essvi_psi.values) / c_.essvi_psi.values[:-1]).min() * 100)
_rho_j = _percap(tf_, 'essvi_g05', lambda c_: np.abs(np.diff(c_.essvi_rho.values)).max())
_rho_s = _percap(tf_, 'essvi', lambda c_: np.abs(np.diff(c_.essvi_rho.values)).max())
_dop = tb_[(tb_.barrier_type == 'out') & (tb_.barrier_dir == 'down') & (tb_.right == 'P')
           & (tb_.maturity == '6M') & tb_.model.isin(['essvi_sg05', 'essvi_g05', 'essvi_gfree', 'essvi'])]
_pv = _dop.pivot_table(index=['ticker', 'date', 'barrier_mult'], columns='model', values='pv').dropna()
_spot = _dop.groupby(['ticker', 'date', 'barrier_mult']).spot.first().reindex(_pv.index)
def _gap(a_, b_):
    return ((_pv[a_] - _pv[b_]).abs() / _spot * 1e4)
_disp = ((_pv.max(axis=1) - _pv.min(axis=1)) / _spot * 1e4)
def _byname(s_):
    return s_.groupby(level='ticker').median() if isinstance(s_.index, pd.MultiIndex) else s_.groupby('ticker').v.median()
W(r'\begin{table}[tbp]')
W(r'\centering')
W(r'\caption{\textbf{Two thin chains beside two from the panel (daily slice).} '
  r'JPM and XOM are run through the identical pipeline as an extension and enter '
  r'no pooled statistic. Panel A describes the chain and the pinned joint arm{\textquotesingle}s '
  r'fit; Panel B the consequences for admissibility, local volatility and the '
  r'six-month down-and-out put. Medians over the nineteen sessions.}')
W(r'\label{tab:thin}')
W(r'\small')
W(r'\textit{Panel A: the chain, and the pinned joint arm}\\[3pt]')
W(r'\setlength{\tabcolsep}{4pt}')
W(r'\begin{tabular}{lrrrrrrrr}')
W(r'\toprule')
W(r'Name & Pillars & Quotes & \shortstack{$\min\Delta\psi/\psi$\\(\%)} & '
  r'\shortstack{$\max|\Delta\rho|$\\joint} & \shortstack{$\max|\Delta\rho|$\\seq.} & '
  r'\shortstack{Fit\\bp} & LOO/IS & \shortstack{ATM bias\\bp} \\')
W(r'\midrule')
for grp, names in [('Extension', THIN), ('Panel', THINREF)]:
    W(r'\multicolumn{9}{l}{\textit{' + grp + r'}} ' + BS + BS)
    for t in names:
        W(r'\quad ' + t
          + ' & ' + f(med(tp_[tp_.ticker == t].n_expiries_used), 0)
          + ' & ' + f(med(tp_[tp_.ticker == t].n_quotes_used), 0)
          + ' & ' + f(med(_psi_inc[_psi_inc.ticker == t].v), 1)
          + ' & ' + f(med(_rho_j[_rho_j.ticker == t].v), 2)
          + ' & ' + f(med(_rho_s[_rho_s.ticker == t].v), 2)
          + ' & ' + f(med(tf_[(tf_.ticker == t) & (tf_.model == 'essvi_g05')].fit_rmse_vol_bp), 1)
          + ' & ' + f(med(tlo_[(tlo_.ticker == t) & (tlo_.model == 'essvi_g05')].ratio), 2)
          + ' & ' + f(med(tlo_[(tlo_.ticker == t) & (tlo_.model == 'essvi_g05')].loo_atm_signed_bp), 1)
          + ' ' + BS + BS)
W(r'\bottomrule')
W(r'\end{tabular}')
W(r'\\[10pt]')
W(r'\textit{Panel B: consequences}\\[3pt]')
W(r'\begin{tabular}{lrrrrrrrr}')
W(r'\toprule')
W(r'& \multicolumn{3}{c}{Crossings (\%)} & \multicolumn{2}{c}{Rough.\ $\times10^{4}$} & \multicolumn{3}{c}{6M down-and-out put (bp)} \\')
W(r'\cmidrule(lr){2-4}\cmidrule(lr){5-6}\cmidrule(lr){7-9}')
W(r'Name & S-eSSVI & \shortstack{G-eSSVI\\$\gamma{=}\tfrac12$} & seq. & joint & seq. & \shortstack{Enforce\\gap} & \shortstack{Greedy\\gap} & \shortstack{Menu\\disp.} \\')
W(r'\midrule')
def _cross(t, mdl):
    s_ = ta_[(ta_.ticker == t) & (ta_.model == mdl)].calendar_crossings
    return f(100 * float((s_ > 0).mean()), 0) if len(s_) else '--'
for grp, names in [('Extension', THIN), ('Panel', THINREF)]:
    W(r'\multicolumn{9}{l}{\textit{' + grp + r'}} ' + BS + BS)
    for t in names:
        W(r'\quad ' + t
          + ' & ' + _cross(t, 'essvi_sg05') + ' & ' + _cross(t, 'essvi_g05') + ' & ' + _cross(t, 'essvi')
          + ' & ' + f(1e4 * med(tl_[(tl_.ticker == t) & (tl_.model == 'essvi_g05')].roughness_mean_abs_d2), 2)
          + ' & ' + f(1e4 * med(tl_[(tl_.ticker == t) & (tl_.model == 'essvi')].roughness_mean_abs_d2), 2)
          + ' & ' + f(_gap('essvi_g05', 'essvi').groupby(level='ticker').median().get(t, np.nan), 1)
          + ' & ' + f(_gap('essvi_sg05', 'essvi_g05').groupby(level='ticker').median().get(t, np.nan), 1)
          + ' & ' + f(_disp.groupby(level='ticker').median().get(t, np.nan), 1)
          + ' ' + BS + BS)
W(r'\bottomrule')
W(r'\end{tabular}')
W('')
W(r'\begin{minipage}{\textwidth}\footnotesize\vspace{0.4em}')
W(r'$\min\Delta\psi/\psi$ is the smallest relative increment of the fitted skew scale '
  r'between adjacent pillars and $\max|\Delta\rho|$ the largest adjacent step in $\rho$, '
  r'each per capture, for the pinned joint arm (joint) and the penalty fit (seq.). '
  r'\emph{Fit}, \emph{LOO/IS} and \emph{ATM bias} are as in Tables~\ref{tab:fit} '
  r'and~\ref{tab:loo}. \emph{Crossings} is the share of name-days with a calendar '
  r'crossing on the grid, as in Table~\ref{tab:arbitrage}. The three gaps are the '
  r'enforcement gap, the greedy gap and the spread over the four eSSVI arms of Table~\ref{tab:barriers-byname}, in bp of spot.')
W(r'\end{minipage}')
W(r'\end{table}')
W('')

# =========================================================== TABLE 3: timing
block('cost')
def tim_block(d, ticks):
    rows = {}
    for m in MODELS:
        x = d[(d.model == m) & d.ticker.isin(ticks)]
        rows[m] = dict(
            n=len(x), dim=med(x.dim), cold=med(x.cold_ms),
            c25=pc(x.cold_ms, 25), c75=pc(x.cold_ms, 75),
            it=med(x.cold_iterations))
    return rows
td_i, td_s = tim_block(tim, IDX), tim_block(tim, SGL)
ti_i, ti_s = tim_block(timi, IDX), tim_block(timi, SGL)

W(r'\begin{table}[tbp]')
W(r'\centering')
W(r'\caption{\textbf{What each calibration costs.} Wall-clock milliseconds per capture, '
  r'median [IQR], for one independent fit from the standard starting point, '
  r'single-threaded within a fit. Split by family because the joint problem scales with '
  r'the expiry count.}')
W(r'\label{tab:timing}')
W(r'\footnotesize')
W(r'\setlength{\tabcolsep}{3.6pt}')
W(r'\begin{tabular}{lrrrrrrrr}')
W(r'\toprule')
W(r'& \multicolumn{4}{c}{Index ETFs} & \multicolumn{4}{c}{Single names} \\')
W(r'\cmidrule(lr){2-5}\cmidrule(lr){6-9}')
W(r'Model & Dim & ms & IQR & Iter. & Dim & ms & IQR & Iter. \\')
W(r'\midrule')
for lab, blkI, blkS in [('Daily slice', td_i, td_s), ('Intraday slice', ti_i, ti_s)]:
    W(r'\multicolumn{9}{l}{\textit{' + lab + r'}} \\')
    for m in MODELS:
        a, b = blkI[m], blkS[m]
        W(f'\\quad {MNAME[m]} & {f(a["dim"],0)} & {f(a["cold"],0)} & '
          f'[{f(a["c25"],0)}, {f(a["c75"],0)}] & {f(a["it"],0)} & '
          f'{f(b["dim"],0)} & {f(b["cold"],0)} & '
          f'[{f(b["c25"],0)}, {f(b["c75"],0)}] & {f(b["it"],0)} \\\\')
    if lab.startswith('Daily'):
        W(r'\addlinespace')
W(r'\bottomrule')
W(r'\end{tabular}')
W('')
W(r'\begin{minipage}{\textwidth}\footnotesize\vspace{0.4em}')
spy_g = tim[(tim.model == 'essvi_g05') & (tim.ticker == 'SPY')]
spy_f = tim[(tim.model == 'essvi_gfree') & (tim.ticker == 'SPY')]
W(r'Dimension of the global problem: $2N{+}1$ parameters for $N$ expiries with '
  r'$\gamma$ fixed, one more with $\gamma$ free. Iterations are Levenberg--Marquardt '
  r'steps.')
W(r'\end{minipage}')
W(r'\end{table}')
W('')

# =========================================================== TABLE 4: arbitrage
block('arb')
ao  = arb[arb.status == 'ok'].copy()
aoi = arbi[arbi.status == 'ok'].copy()

W(r'\begin{table}[tbp]')
W(r'\centering')
gl_cross = float(ao[ao.model.isin(GUARANTEED)].fit_max_calendar_crossing.max())
gl_txt = ('exactly $0$' if gl_cross == 0.0
          else '$' + f'{gl_cross:.1e}'.replace('e-0', r'\times10^{-').replace('e-', r'\times10^{-') + '}$')
W(r'\caption{\textbf{Static arbitrage of the fitted surfaces.} Share of fitted '
  r'name-days with at least one butterfly violation or calendar crossing, measured on '
  r'the full $(k,t)$ grid. Panel B gives, for each '
  r'name, the share of its captures carrying at least one calendar crossing.}')
W(r'\label{tab:arbitrage}')
W(r'\small')
W(r'\textit{Panel A: by arm, share of name-days with at least one violation}\\[3pt]')
W(r'\begin{tabular}{lrrrrr}')
W(r'\toprule')
W(r'& & \multicolumn{2}{c}{Butterfly} & \multicolumn{2}{c}{Calendar} \\')
W(r'\cmidrule(lr){3-4}\cmidrule(lr){5-6}')
W(r'Model & Days & $n$ & \% & $n$ & \% \\')
W(r'\midrule')
for lab, d in [('Daily slice', ao), ('Intraday slice', aoi)]:
    W(r'\multicolumn{6}{l}{\textit{' + lab + r'}} \\')
    for mm in MODELS:
        x = d[d.model == mm]
        bf, cl = (x.butterfly_violations > 0), (x.calendar_crossings > 0)
        W('\\quad ' + MNAME[mm] + f' & {n_(len(x), x)} & {n_(bf.sum(), x)} & '
          f'{f(100*bf.mean(),1)} & {n_(cl.sum(), x)} & {f(100*cl.mean(),1)} \\\\')
    if lab.startswith('Daily'):
        W(r'\addlinespace')
W(r'\bottomrule')
W(r'\end{tabular}')
W(r'\\[10pt]')
W(r'\textit{Panel B: calendar crossings by name, share of captures}\\[3pt]')
W(r'\setlength{\tabcolsep}{4pt}')
W(r'\begin{tabular}{lr' + 'r'*len(MODELS) + '}')
W(r'\toprule')
W('Name & Caps. & ' + ' & '.join(r'\shortstack{' + MSTACK[mm][0] + r'\\' + MSTACK[mm][1] + '}' for mm in MODELS) + r' \\')
W(r'\midrule')
for lab, d in [('Daily slice', ao), ('Intraday slice', aoi)]:
    W(r'\multicolumn{' + str(2 + len(MODELS)) + r'}{l}{\textit{' + lab + r'}} \\')
    rows = [(t, d[d.ticker == t]) for t in TICKS] + [('All', d)]
    for nm, x in rows:
        if nm == 'All':
            W(r'\addlinespace')
        cells = [f(100 * (x[x.model == mm].calendar_crossings > 0).mean(), 0) + r'\%' for mm in MODELS]
        W('\\quad ' + nm + f' & {n_(len(x[x.model == chr(115)+chr(118)+chr(105)]), x)} & '
          + ' & '.join(cells) + r' \\')
    if lab.startswith('Daily'):
        W(r'\addlinespace')
W(r'\bottomrule')
W(r'\end{tabular}')
W(r'\end{table}')
W('')

# =========================================================== TABLE 5: local vol
block('localvol')
lo  = lv[lv.status.str.startswith('ok')].copy()
loi = lvi[lvi.status.str.startswith('ok')].copy()
DK = lv.roughness_dk.dropna().unique()[0]

W(r'\begin{table}[tbp]')
W(r'\centering')
W(r'\caption{\textbf{The induced Dupire local volatility, name by name.} Panel A: '
  r'curvature roughness of $\sigma_{\mathrm{loc}}$ per ticker. Panel B: clamp activity '
  r'against the $[0.01, 3.0]$ bounds, the local-volatility range, and the '
  r'finite-difference round trip back to each arm{\textquotesingle}s own smile. '
  r'Definitions in the footnote.}')
W(r'\label{tab:localvol}')
W(r'\footnotesize')
W(r'\setlength{\tabcolsep}{1.5pt}')
W(r'\begin{tabular}{lrrrrrrrrr}')
W(r'\toprule')
W(r'\multicolumn{10}{l}{\textit{Panel A: roughness $\times 10^{4}$, median by name '
  r'(daily slice)}} \\')
W(r'Model & ' + ' & '.join(TICKS) + r' & All [IQR] \\')
W(r'\midrule')
for m in MODELS:
    x = lo[lo.model == m]
    rg = 1e4 * x.roughness_mean_abs_d2
    by_t = ' & '.join(
        f(1e4 * med(x[x.ticker == t].roughness_mean_abs_d2), 2)
        for t in TICKS)
    W('\\quad ' + MNAME[m] + ' & ' + by_t + ' & '
      + f(med(rg), 2) + ' [' + f(pc(rg, 25), 2) + ', ' + f(pc(rg, 75), 2) + '] \\\\')
W(r'\midrule')
W(r'\multicolumn{10}{l}{\textit{Panel B: containment and round trip}} \\')
W(r'& \multicolumn{4}{c}{Daily slice} & & \multicolumn{4}{c}{Intraday slice} \\')
W(r'\cmidrule(lr){2-5}\cmidrule(lr){7-10}')
W(r'Model & Clamped & $\sigma_{\min}$ & $\sigma_{\max}$ & \shortstack{Round\\trip bp} & & '
  r'Rough.\ All [IQR] & Clamped & $\sigma_{\max}$ & \shortstack{Round\\trip bp} \\')
W(r'\midrule')
for m in MODELS:
    x = lo[lo.model == m]
    xi_ = loi[loi.model == m]
    rgi = 1e4 * xi_.roughness_mean_abs_d2
    W('\\quad ' + MNAME[m] + ' & '
      + f(med(100 * x.clamped_fraction), 2) + '\\% & '
      + f(med(x.lv_min), 3) + ' & ' + f(med(x.lv_max), 3) + ' & '
      + f(med(x.rt_vs_fit_mean_vol_bp), 1) + ' & & '
      + f(med(rgi), 2) + ' [' + f(pc(rgi, 25), 2) + ', ' + f(pc(rgi, 75), 2) + '] & '
      + f(med(100 * xi_.clamped_fraction), 2) + '\\% & '
      + f(med(xi_.lv_max), 3) + ' & '
      + f(med(xi_.rt_vs_fit_mean_vol_bp), 1) + ' \\\\')
W(r'\bottomrule')
W(r'\end{tabular}')
W('')
W(r'\begin{minipage}{\textwidth}\footnotesize\vspace{0.4em}')
W(r'\emph{Roughness} is $10^{4}\,\mathrm{mean}_{(k,t)}\,\big|\sigma_{\mathrm{loc}}(k+\Delta k,t) '
  r'- 2\sigma_{\mathrm{loc}}(k,t) + \sigma_{\mathrm{loc}}(k-\Delta k,t)\big|$ over the shared '
  r'grid, at $\Delta k = ' + f(DK, 2) + r'$; a value of 3 means '
  r'neighbouring-strike deviations of about 3 vol basis points from the local line. '
  r'\emph{Clamped} is the median share of grid cells pinned at the $[0.01, 3.0]$ '
  r'bounds. $\sigma_{\min}$ and $\sigma_{\max}$ are medians of the per-day '
  r'extremes, so day-level tail events do not appear in them. \emph{Round trip bp} is '
  r'Crank--Nicolson local-vol repricing of the calibrating vanillas, re-inverted to '
  r'implied vol, against the arm{\textquotesingle}s own fitted smile.')
W(r'\end{minipage}')
W(r'\end{table}')
W('')

# =========================================================== TABLE 6: martingale
mo  = mart[mart.status == 'ok'].copy()
moi = marti[marti.status == 'ok'].copy()
for d in (mo, moi):
    d['abp']   = d.relative_error.abs() * 1e4
    d['az']    = d.z_score.abs()
    d['below'] = tobool(d.t_below_first_pillar.astype(str).str.lower()).astype(bool)
PATHS = int(mo.paths.iloc[0]); SEED = int(mo.seed.iloc[0]); SPY_ = int(mo.steps_per_year.iloc[0])

# The martingale gate separates nothing, so its table lives in the
# appendix, pooled across horizons; the main text carries three sentences.
block('martingale')
W(r'\begin{table}[tbp]')
W(r'\centering')
_mo_ = mart[mart.status == 'ok']; _mi_ = marti[marti.status == 'ok']
_nzd = int((_mo_.z_score.abs() > 3).sum()); _nzi = int((_mi_.z_score.abs() > 3).sum())
_ztxt = (('no daily cell' if _nzd == 0 else f'{_nzd} daily cells') + ' and ' +
         ('no intraday cell' if _nzi == 0 else f'{_nzi} intraday cells (' + f(100*_nzi/len(_mi_), 2) + r'\%, against 0.27\% under normality)'))
W(r'\caption{\textbf{Martingale check, per arm.} Absolute relative error '
  r'$|\mathbb{E}[S_T]/F_T-1|$ in basis points, and $|z|$, pooled across the 1M, '
  r'3M and 6M horizons; both are defined in Section~\ref{sec:res-martingale}.}')
W(r'\label{tab:martingale}')
W(r'\small')
W(r'\begin{tabular}{lrrrrrrrr}')
W(r'\toprule')
W(r'& \multicolumn{4}{c}{Daily} & \multicolumn{4}{c}{Intraday} \\')
W(r'\cmidrule(lr){2-5}\cmidrule(lr){6-9}')
W(r'Model & $n$ & Med.\ bp & p99 bp & max $|z|$ '
  r'& $n$ & Med.\ bp & p99 bp & max $|z|$ \\')
W(r'\midrule')
def mart_row(label, xd, xi):
    W(f'{label} & {n_(len(xd), xd)} & {f(med(xd.abp),2)} & {f(pc(xd.abp,99),1)} & '
      f'{f(xd.az.max(),2)} & {n_(len(xi), xi)} & {f(med(xi.abp),2)} & '
      f'{f(pc(xi.abp,99),1)} & {f(xi.az.max(),2)} \\\\')
for m in MODELS:
    mart_row(MNAME[m], mo[mo.model == m], moi[moi.model == m])
W(r'\midrule')
mart_row('All', mo, moi)
W(r'\bottomrule')
W(r'\end{tabular}')
W(r'\end{table}')
A('')

# =========================================================== TABLE 7: barriers
block('barriers_byname')
BCOLS = ['ticker', 'date', 'time', 'model', 'status', 'maturity', 't_below_first_pillar',
         't_beyond_last_pillar', 'spot', 'barrier_type', 'barrier_dir', 'barrier_mult',
         'right', 'pv', 'std_err', 'paths', 'seed']

def barrier_load(path):
    b = rcsv(path, usecols=BCOLS)
    b = b[b.status == 'ok'].copy()
    b['bm'] = b.barrier_mult.fillna(0.0)
    b['below'] = tobool(b.t_below_first_pillar.astype(str).str.lower()).astype(bool)
    b['beyond'] = tobool(b.t_beyond_last_pillar.astype(str).str.lower()).fillna(False).astype(bool)
    b['prod'] = [('Vanilla ' if r.barrier_type == 'none' else
                  ('Down-and-out ' if r.barrier_dir == 'down' else 'Up-and-out ')) +
                 ('call' if r.right == 'C' else 'put') for r in b.itertuples()]
    return b

def spread_over(b, models):
    x = b[b.model.isin(models)]
    key = ['ticker', 'date', 'time', 'maturity', 'prod', 'bm']
    g = (x.groupby(key, dropna=False)
           .agg(n=('pv', 'size'), mn=('pv', 'min'), mx=('pv', 'max'), mean=('pv', 'mean'),
                se=('std_err', 'mean'), spot=('spot', 'first'),
                below=('below', 'max'), beyond=('beyond', 'max')).reset_index())
    g = g[g.n == len(models)].copy()
    g['rel'] = (g.mx - g.mn) / g['mean'] * 100
    g['absbp'] = (g.mx - g.mn) / g.spot * 1e4
    g['sig'] = (g.mx - g.mn) / g.se
    g['pricebp'] = g['mean'] / g.spot * 1e4
    g['sebp'] = g.se / g.spot * 1e4
    return g

def pair_gap(b, m1, m2):
    key = ['ticker', 'date', 'time', 'maturity', 'prod', 'bm']
    p1 = b[b.model == m1].set_index(key)[['pv', 'spot', 'se_' if False else 'std_err', 'below', 'beyond']]
    p2 = b[b.model == m2].set_index(key)[['pv']]
    j = p1.join(p2, rsuffix='_2', how='inner').reset_index()
    j['rel'] = (j.pv - j.pv_2).abs() / ((j.pv + j.pv_2) / 2) * 100
    j['absbp'] = (j.pv - j.pv_2).abs() / j.spot * 1e4
    j['sig'] = (j.pv - j.pv_2).abs() / j.std_err
    return j

braw = barrier_load(f'{R}/barriers.csv')
BPATHS = int(rcsv(f'{R}/barriers.csv', usecols=['paths']).paths.dropna().iloc[0])
BSEED = int(rcsv(f'{R}/barriers.csv', usecols=['seed']).seed.dropna().iloc[0])

ESSVI = ['essvi_sg05', 'essvi_g05', 'essvi_gfree', 'essvi']   # the four eSSVI arms
menu = spread_over(braw, ESSVI);   menu_cal = menu[~menu.below & ~menu.beyond]
QMENU = ['essvi_sg05', 'essvi', 'ssvi']   # the arms that take theta from the quotes
qmenu = spread_over(braw, QMENU);  qmenu_cal = qmenu[~qmenu.below & ~qmenu.beyond]
alls = spread_over(braw, MODELS);  alls_cal = alls[~alls.below & ~alls.beyond]
g_pair = pair_gap(braw, 'essvi_g05', 'essvi_gfree'); g_cal = g_pair[~g_pair.below & ~g_pair.beyond]
s_pair = pair_gap(braw, 'essvi_g05', 'essvi');       s_cal = s_pair[~s_pair.below & ~s_pair.beyond]
q_pair = pair_gap(braw, 'essvi_sg05', 'essvi_g05');  q_cal = q_pair[~q_pair.below & ~q_pair.beyond]
r_pair = pair_gap(braw, 'essvi_sg05', 'essvi');      r_cal = r_pair[~r_pair.below & ~r_pair.beyond]

# Reported products: the two knock-outs that read the two wings, plus one
# vanilla control. The mirrored families (down-and-out call, up-and-out
# put) and the vanilla put behave alike and stay in the released CSVs.
PRODS = ['Down-and-out put', 'Up-and-out call', 'Vanilla call']
dop = menu_cal[(menu_cal['prod'] == 'Down-and-out put') & (menu_cal.maturity == '6M')]
van = menu_cal[(menu_cal['prod'] == 'Vanilla call') & (menu_cal.maturity == '6M')]
gd  = g_cal[(g_cal['prod'] == 'Down-and-out put') & (g_cal.maturity == '6M')]

W(r'\begin{table}[tbp]')
W(r'\centering')
W(r'\caption{\textbf{The out-of-the-money design of Table~\ref{tab:barriers}, by name and by choice.} Struck half an at-the-money '
  r'standard deviation into the wing with the barrier a full one from the forward, '
  r'$K = F\exp(\pm\tfrac12\sigma\sqrt{T})$, $H = F\exp(\pm\sigma\sqrt{T})$, priced by every arm on one '
  r'shared path set; the vanilla at the same strike is priced in closed form at each '
  r'arm{\textquotesingle}s fitted vol. \emph{Premium} is the mean price over the four eSSVI arms. '
  r'\emph{Spread} is $\max-\min$ over the four eSSVI arms (S-eSSVI, the two G-eSSVI arms, '
  r'sequential eSSVI); the three gaps are $|a-b|$ for one choice at a time. Everything in basis points of '
  r'spot, medians over the nineteen sessions; MC $\sigma$ is the median Monte Carlo standard '
  r'error of one price. ' + i(BPATHS) + r' antithetic paths per price, seed ' + str(BSEED) + r'.}')
W(r'\label{tab:barriers-byname}')
W(r'\small')
W(r'\setlength{\tabcolsep}{4pt}')
W(r'\begin{tabular}{lrrrrrr}')
W(r'\toprule')
W(r'Name & Premium & Spread & \shortstack{Pin\\$\gamma{=}\tfrac12$ vs free} & '
  r'\shortstack{Enforce\\joint vs pen.} & \shortstack{Greedy\\vs joint} & MC $\sigma$ \\')
W(r'\midrule')
def _sel(d, prod, t):
    x = d[(d['prod'] == prod) & (d.maturity == '6M')]
    return x if t == 'All' else x[x.ticker == t]
for prod, title in [('Down-and-out put', 'Panel A: down-and-out put'),
                    ('Up-and-out call', 'Panel B: up-and-out call'),
                    ('Vanilla call', 'Panel C: vanilla call at the same strike, closed form at the fitted vol')]:
    W(r'\multicolumn{7}{l}{\textit{' + title + r'}} \\')
    for t in TICKS + ['All']:
        x = _sel(menu_cal, prod, t); q = _sel(qmenu_cal, prod, t)
        a_ = _sel(g_cal, prod, t); b_ = _sel(s_cal, prod, t); c_ = _sel(q_cal, prod, t)
        W((r'\quad ' if t != 'All' else '') + t
          + ' & ' + f(med(x.pricebp), 0) + ' & ' + f(med(x.absbp), 1)
          + ' & ' + f(med(a_.absbp), 1) + ' & ' + f(med(b_.absbp), 1) + ' & ' + f(med(c_.absbp), 1)
          + ' & ' + (f(med(x.sebp), 1) if med(x.sebp) > 0 else '--') + r' \\')
    W(r'\addlinespace')
W(r'\bottomrule')
W(r'\end{tabular}')
W(r'\end{table}')
W('')


# ================================================ TABLE: barrier summary
# How much the four eSSVI calibrations disagree on a six-month price,
# (max - min)/mean, for two designs: A strike at the forward
# (barriers_forward.csv), B strike half a standard deviation out of the
# money (barriers.csv); barrier one standard deviation from the forward,
# vanilla in closed form at each arm's fitted vol. Main table: index
# chains (SPY, QQQ, IWM) and single names; a second table: DIA.
block('barriers')
_GRP = {'SPY': 'Index', 'QQQ': 'Index', 'IWM': 'Index', 'DIA': 'DIA',
        'META': 'Single', 'AMD': 'Single', 'TSLA': 'Single', 'GOOGL': 'Single'}
_ESSVI = ['essvi_sg05', 'essvi_g05', 'essvi_gfree', 'essvi']
_QE = ['essvi_sg05', 'essvi']          # the eSSVI arms that take theta from the quotes
def _rel_cells(path, models):
    b = rcsv(path, low_memory=False)
    b = b[(b.status == 'ok') & (b.maturity == '6M')].copy()
    b['barrier_dir'] = b.barrier_dir.fillna('none')
    b['kind'] = [('Vanilla ' if r.barrier_type == 'none' else ('Up-and-out ' if r.barrier_dir == 'up' else 'Down-and-out '))
                 + ('call' if r.right == 'C' else 'put') for r in b.itertuples()]
    x = b[b.model.isin(models)]
    g = x.groupby(['ticker', 'date', 'kind'], dropna=False).agg(
        n=('pv', 'size'), mn=('pv', 'min'), mx=('pv', 'max'), mean=('pv', 'mean'), spot=('spot', 'first')).reset_index()
    g = g[g.n == len(models)].copy()
    g['prem'] = g['mean'] / g.spot * 100
    g['rel'] = (g.mx - g.mn) / g['mean'] * 100
    g['abs'] = (g.mx - g.mn) / g.spot * 1e4
    g['grp'] = g.ticker.map(_GRP)
    return g
_designs = [
    ('Panel A: at the money, $K = F$', f'{R}/barriers_forward.csv',
     [('Vanilla (call $=$ put)', 'Vanilla call'), ('Up-and-out call', 'Up-and-out call'), ('Down-and-out put', 'Down-and-out put')]),
    (r'Panel B: out of the money, $K = F\exp(\pm\tfrac12\sigma\sqrt{T})$', f'{R}/barriers.csv',
     [('Vanilla call', 'Vanilla call'), ('Up-and-out call', 'Up-and-out call'),
      ('Vanilla put', 'Vanilla put'), ('Down-and-out put', 'Down-and-out put')]),
]
_CONTRACT = (r'Barrier $H = F\exp(\pm\sigma\sqrt{T})$ in both panels, $\sigma$ the market at-the-money '
             r'vol; knock-outs priced by every arm on one shared path set, the vanilla at the same strike '
             r'in closed form at each arm{\textquotesingle}s fitted vol.')
W(r'\begin{table}[tbp]')
W(r'\centering')
W(r'\caption{\textbf{Calibration disagreement on six-month prices.} '
  r'$(\max-\min)/\mathrm{mean}$ over the four eSSVI arms (S-eSSVI, the two G-eSSVI arms, '
  r'sequential eSSVI), in percent of the price; median and 90th percentile over name-days. '
  + _CONTRACT + r' \emph{Premium} is the median mean price, in percent of spot. \emph{Index} is '
  r'SPY, QQQ and IWM; DIA is in Table~\ref{tab:barriers-dia}.}')
W(r'\label{tab:barriers}')
W(r'\small')
W(r'\setlength{\tabcolsep}{5pt}')
W(r'\begin{tabular}{lrrrrrr}')
W(r'\toprule')
W(r'& \multicolumn{3}{c}{Index} & \multicolumn{3}{c}{Single names} \\')
W(r'\cmidrule(lr){2-4}\cmidrule(lr){5-7}')
W(r'& \shortstack{Premium\\(\% spot)} & \shortstack{Median\\(\%)} & \shortstack{p90\\(\%)} '
  r'& \shortstack{Premium\\(\% spot)} & \shortstack{Median\\(\%)} & \shortstack{p90\\(\%)} \\')
W(r'\midrule')
_BCELLS = {}
for title, path, rows in _designs:
    g = _rel_cells(path, _ESSVI); _BCELLS[title] = (g, _rel_cells(path, _QE))
    W(r'\multicolumn{7}{l}{\textit{' + title + r'}} \\')
    for lab, kind in rows:
        cells_ = []
        for grp in ('Index', 'Single'):
            x = g[(g.kind == kind) & (g.grp == grp)]
            cells_ += [f(med(x.prem), 2), f(med(x.rel), 1), f(pc(x.rel, 90), 1)]
        W(r'\quad ' + lab + ' & ' + ' & '.join(cells_) + r' \\')
    W(r'\addlinespace')
W(r'\bottomrule')
W(r'\end{tabular}')
W(r'\end{table}')
W('')
W(r'\begin{table}[tbp]')
W(r'\centering')
W(r'\caption{\textbf{The same contracts on DIA.} As Table~\ref{tab:barriers}. \emph{bp} is the '
  r'spread in basis points of spot; \emph{Quoted $\theta$} is the median spread between the two '
  r'eSSVI arms that take $\theta$ from the quoted ATM variance (S-eSSVI and sequential eSSVI), '
  r'which share the at-the-money level and differ only in the wings and between pillars.}')
W(r'\label{tab:barriers-dia}')
W(r'\small')
W(r'\setlength{\tabcolsep}{5pt}')
W(r'\begin{tabular}{lrrrrr}')
W(r'\toprule')
W(r'& \shortstack{Premium\\(\% spot)} & \shortstack{Median\\(\%)} & \shortstack{p90\\(\%)} & bp '
  r'& \shortstack{Quoted $\theta$\\(\%)} \\')
W(r'\midrule')
for title, path, rows in _designs:
    g, q = _BCELLS[title]
    W(r'\multicolumn{6}{l}{\textit{' + title + r'}} \\')
    for lab, kind in rows:
        x = g[(g.kind == kind) & (g.grp == 'DIA')]; y = q[(q.kind == kind) & (q.grp == 'DIA')]
        W(r'\quad ' + lab + ' & ' + f(med(x.prem), 2) + ' & ' + f(med(x.rel), 1) + ' & '
          + f(pc(x.rel, 90), 1) + ' & ' + f(med(x['abs']), 1) + ' & ' + f(med(y.rel), 1) + r' \\')
    W(r'\addlinespace')
W(r'\bottomrule')
W(r'\end{tabular}')
W(r'\end{table}')
W('')

for _name, _b in blocks.items():
    _p = os.path.join(_HERE, 'tables_' + _name + '.tex').replace('\\', '/')
    open(_p, 'w', encoding='utf-8').write('\n'.join(_b) + '\n')
    print('wrote', _p, len(_b), 'lines')
_stale = os.path.join(_HERE, 'tables.tex')
if os.path.exists(_stale):
    os.remove(_stale)
    print('removed stale tables.tex')
open(TEXA, 'w', encoding='utf-8').write('\n'.join(outA) + '\n')
print('wrote', TEXA, len(outA), 'lines')

# --------------------------------------------------- console reconciliation dump
print('\n=== RECONCILIATION ===')
print('daily captures', len(panel), 'ok', (panel.status == 'ok').sum())
print('intraday captures', len(paneli), 'ok', (paneli.status == 'ok').sum())
for m in MODELS:
    s = fo[fo.model == m]
    print(f'FIT {m:12s}: med {med(s.fit_rmse_vol_bp):8.2f} p90 {pc(s.fit_rmse_vol_bp,90):9.2f}  n {len(s)}')
print('gamma fitted: med %.4f  IQR %.4f-%.4f' % (med(gam), pc(gam,25), pc(gam,75)))
for m in MODELS:
    x = lo[lo.model == m]
    print(f'LV  {m:12s}: rough {med(x.roughness_mean_abs_d2):.3e} clamp>0 {100*(x.clamped_fraction>0).mean():5.1f}% '
          f'rt {med(x.rt_vs_fit_mean_vol_bp):6.2f}')
for m in MODELS:
    a, b = td_i[m], td_s[m]
    print(f'TIM {m:12s}: cold idx {a["cold"]:8.1f} ms / sgl {b["cold"]:8.1f} ms')
print('MART all daily: med %.3f bp  z>3 %.3f%%' % (med(mo.abp), 100*(mo.az>3).mean()))
print('BAR 6M DOP menu: rel %.2f%%  abs %.2f bp  n %d' % (med(dop.rel), med(dop.absbp), len(dop)))
print('BAR 6M DOP g05-vs-gfree: %.2f%%   g05-vs-seq: %.2f%%' % (
    med(gd.rel), med(s_cal[(s_cal["prod"]=="Down-and-out put") & (s_cal.maturity=="1M")].rel)))
